### ISSUE TITLE
COPY failed: no source files were specified

### ISSUE THREAD

**Issue by ozitraveller** [dotnet/dotnet-docker-samples#85] opened 2017-10-09 21:56 UTC
I tried your example dotnetapp-prod, and that worked ok. But I tried one of my vs 2017 solutions and that failed.

Any suggestions?

Microsoft Visual Studio Enterprise 2017 
Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16

Docker version 17.09.0-ce, build afdb6d4

Sending build context to Docker daemon  8.445MB
Step 1/10 : FROM microsoft/dotnet:2.0-sdk AS build-env
 ---> 2d1d3b4f6d02
Step 2/10 : WORKDIR /app
 ---> 410cfa3ce12b
Removing intermediate container 517f7d909176
Step 3/10 : COPY *.csproj ./
COPY failed: no source files were specified

**Comment by ravimeda** [comment] 2017-10-10 21:40
@ozitraveller thanks for trying .NET Core Docker Production Sample. 

About the issue with VS 2017 project, please could you clarify if the folder that contains Dockerfile has a `.csproj` file. Notice that in the sample (https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod) Dockerfile and the `.csproj` are in the same folder.

**Comment by ozitraveller** [comment] 2017-10-11 00:02
@ravimeda yes both the dockerfile and .csproj are in the same folder.

**Comment by ravimeda** [comment] 2017-10-11 03:57
Thanks for confirming. To help me investigate, please could you provide a simple set of steps to reproduce the issue. Include environment details such as `docker version`

**Comment by ozitraveller** [comment] 2017-10-11 05:56
Docker version 17.09.0-ce, build afdb6d4 same as above.

I started with your dockerfile in a VS2017 .netcore 2.0 webapi solution with docker support enabled. 

FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
RUN dotnet publish -c Release -o out

In the folder with the dockerfile I did the docker build command below:

docker build -t test-build .
Sending build context to Docker daemon  8.445MB
Step 1/11 : FROM microsoft/dotnet:2.0-sdk AS build-env
 ---> 2d1d3b4f6d02
Step 2/11 : WORKDIR /app
 ---> 6a8fac427567
Removing intermediate container 9057fce8fdba
Step 3/11 : COPY *.csproj ./
COPY failed: no source files were specified

**Comment by ravimeda** [comment] 2017-10-11 15:53
Thanks very much. Yes, I can reproduce this locally. 

Steps:

1. Launch VS 2017
2. Create new project. Select `ASP.NET Core Web Application` template
3. Select `Web API`. Check `Enable Docker Support`
4. Save and close the project
5. Replace Dockerfile with the content from https://github.com/dotnet/dotnet-docker-samples/blob/master/dotnetapp-prod/Dockerfile
6. Launch PowerShell. Navigate to the project folder. Run `docker build -t test-build .`

Here I get the error -
```
Step 3/10 : COPY *.csproj ./
COPY failed: no source files were specified
```

This is because of `.dockerignore` file that ignores the `csproj`. Notice the content of `.dockerignore` is -
```
*
!obj/Docker/publish/*
!obj/Docker/empty/
```

Anything other than `obj/Docker/publish/*` and `obj/Docker/empty` is ignored. This is because Tools for Docker (https://docs.microsoft.com/en-us/aspnet/core/publishing/visual-studio-tools-for-docker) builds and publishes the output to a volume (obj/Docker). This output is used for the runtime.

Whereas, .NET Core Sample (https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod) uses multi-stage build approach that builds the app using the SDK image, copies the build output to a runtime image. Observe the lines (https://github.com/dotnet/dotnet-docker-samples/blob/master/dotnetapp-prod/Dockerfile#L13-L15) where the copying happens in the second stage.

Hopefully this clarifies the difference between the two approaches, and you can choose the one that best fits your need.

**Comment by ozitraveller** [comment] 2017-10-11 21:46
@ravimeda Thanks that's awesome. yes I understand the differences between the 2 methods. I need to test further to see if anything is impacted in our azure CI process.

Also, I tried to import "build-pipeline/dotnet-docker-samples-linux-amd64-images.json" into azure but if failed. The error message said it was the wrong format.

**Comment by MichaelSimons** [comment] 2017-10-11 22:04
@ozitraveller - Can you explain what "build-pipeline/dotnet-docker-samples-linux-amd64-images.json" is?

**Comment by MichaelSimons** [comment] 2017-10-11 22:15
@ozitraveller - I realized you are referring to the [build-pipeline](https://github.com/dotnet/dotnet-docker-samples/tree/master/build-pipeline) folder.  As we tried to indicate in the [README.md](https://github.com/dotnet/dotnet-docker-samples/blob/master/build-pipeline/README.md), this is internal infrastructure MSFT uses to build the sample Dockerfiles which are pushed to [microsoft/dotnet-samples](https://hub.docker.com/r/microsoft/dotnet-samples/).  This infrastructure is not intended to be generally used.

**Comment by ozitraveller** [comment] 2017-10-11 22:39
@MichaelSimons - Ok thanks no worries.

**Comment by MichaelSimons** [comment] 2017-10-11 22:53
@ozitraveller - closing issue as it appears your question was answered.  If you have further questions feel free to reopen this issue if related or open a new issue. Thanks

**Closed as completed by MichaelSimons** 2017-10-11 22:53 UTC
Labels: question, triaged

**Comment by kevinwcrump** [comment] 2017-11-29 15:53
@ravimeda - Thanks for explaining. Your post was very helpful.

**Comment by DanJ210** [comment] 2018-02-27 21:55
@ravimeda I'm getting this issue and I'm still a little confused but my question is if I remove `!obj/Docker/publish/*` and `!obj/Docker/empty/` should then the .csproj not get ignored?
