### ISSUE TITLE
lttng-ust-comm.c:1520: lttng_ust_init: Assertion `!ret' failed.

### ISSUE THREAD

**Issue by NigelThorne** [dotnet/dotnet-docker-samples#48] opened 2017-06-06 23:54 UTC
I'm getting a failure when trying to run the sample project. 

```
>docker run microsoft/dotnet-samples
Unable to find image 'microsoft/dotnet-samples:latest' locally
latest: Pulling from microsoft/dotnet-samples
10a267c67f42: Pull complete
fa5522c41f52: Pull complete
1216bf0fa4dc: Pull complete
aeb78899be5e: Pull complete
1084e7db7809: Pull complete
355ff795382a: Pull complete
Digest: sha256:681d2750dde7fd0d589b4be22c4d9780e26a832016ff896144ed124ea216f1ec
Status: Downloaded newer image for microsoft/dotnet-samples:latest
dotnet: lttng-ust-comm.c:1520: lttng_ust_init: Assertion `!ret' failed.

```
rerunning the image I get the same thing. 

```
>docker run microsoft/dotnet-samples
dotnet: lttng-ust-comm.c:1520: lttng_ust_init: Assertion `!ret' failed.
```

**Comment by MichaelSimons** [comment] 2017-06-07 13:37
@NigelThorne, Can you please specify what version of Docker you are using?  Include the output from running `docker version`.

**Comment by sairamkonuru** [comment] 2017-06-07 16:09
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:54:33 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:04:55 2017
 OS/Arch:      windows/amd64
 Experimental: true

**Comment by sairamkonuru** [comment] 2017-06-07 16:09
I have tried with Standard version as well.

**Comment by MichaelSimons** [comment] 2017-06-08 21:41
I am not able to reproduce this issue locally.  Can you include the output of `docker info`?  Wondering if this is possible a host specific issue.

**Comment by MichaelSimons** [comment] 2017-06-21 22:09
@sairamkonuru, please provide the `docker info` output if this is still an issue otherwise please close.

**Comment by NigelThorne** [comment] 2017-06-21 23:04
Yep.. still a problem.  Here is my data. 

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
 
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 25
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 98
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: CAXQ:IQ7B:NGZH:IR6K:5MGJ:QWJ4:IB67:5EDA:LUOL:37FL:QEOL:B4D6
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 22
 System Time: 2017-06-21T23:03:31.853027765Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by MichaelSimons** [comment] 2017-06-22 14:08
@NigelThorne - It looks like you are hitting [this](https://github.com/moby/moby/issues/20818) issue with version of Docker you are using.  Please upgrade the version of Docker you are using.  An alternative workaround is to add the following to your Dockerfile `ENV LTTNG_UST_REGISTER_TIMEOUT 0`.

**Comment by MichaelSimons** [comment] 2017-06-27 21:17
Closing as this appears to be an issue with using an older Docker version.

**Closed as completed by MichaelSimons** 2017-06-27 21:17 UTC
Labels: bug
